tasks:
  - init: |
      echo "Installing AWS CLI..."
      cd ../
      curl -fSsl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -qq awscliv2.zip
      sudo ./aws/install --update
      rm awscliv2.zip
      cd cdn
      echo "Setting up AWS CLI..."
      aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      aws configure set region $AWS_REGION
    command: |
      echo "Starting the development server..."
      pnpm install
      npx sst dev --stage dev
